### ISSUE TITLE
#1 week

### ISSUE THREAD

**Issue by yeeun98** [yeeun98/Nomad_CSS#1]
🖥 노마드 강의
- [x]     #1 INTRODUCTION
- [x]     #2 FLEXBOX
- [x]     #3 GRID

📒 강의 내용 정리
- [x]     #1 INTRODUCTION
- [x]     #2 FLEXBOX
- [x]     #3 GRID

**Comment by Joie-Kim** [comment]
서로서로 이렇게 댓글도 달아주죠 ? 멋져용 ~ 퍼가요 ~
